// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtb9YMEhL1ni73ap6OdDidm5P1f965Xfk',
    appId: '1:245605805965:web:4261acaef84222cffe57c4',
    messagingSenderId: '245605805965',
    projectId: 'authentication-5d5fc',
    authDomain: 'authentication-5d5fc.firebaseapp.com',
    storageBucket: 'authentication-5d5fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsImC5Qinh9Cqv0icMLYM79iX8g1riK4o',
    appId: '1:245605805965:android:69c3b4d2e111a5bdfe57c4',
    messagingSenderId: '245605805965',
    projectId: 'authentication-5d5fc',
    storageBucket: 'authentication-5d5fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvbhX8gLr1wL9bvpSftnXCvahAxEb9vE',
    appId: '1:245605805965:ios:9dda4ba074353043fe57c4',
    messagingSenderId: '245605805965',
    projectId: 'authentication-5d5fc',
    storageBucket: 'authentication-5d5fc.appspot.com',
    iosClientId: '245605805965-59m1dhtkgbdp142aqu76gdc7dnahe1d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.relogioPonto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgvbhX8gLr1wL9bvpSftnXCvahAxEb9vE',
    appId: '1:245605805965:ios:9dda4ba074353043fe57c4',
    messagingSenderId: '245605805965',
    projectId: 'authentication-5d5fc',
    storageBucket: 'authentication-5d5fc.appspot.com',
    iosClientId: '245605805965-59m1dhtkgbdp142aqu76gdc7dnahe1d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.relogioPonto',
  );
}
