// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1yU-7YK36zsWea2YuIDRbeCiZ1eORIAc',
    appId: '1:196881712981:web:9ee43240739048d03611dc',
    messagingSenderId: '196881712981',
    projectId: 'ponto-551a5',
    authDomain: 'ponto-551a5.firebaseapp.com',
    databaseURL: 'https://ponto-551a5-default-rtdb.firebaseio.com',
    storageBucket: 'ponto-551a5.appspot.com',
    measurementId: 'G-ZKKG37EVD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDupTvflO2dAmLf65OgFv8ASpkhNX6OYJQ',
    appId: '1:196881712981:android:0f64fd7def24ec153611dc',
    messagingSenderId: '196881712981',
    projectId: 'ponto-551a5',
    databaseURL: 'https://ponto-551a5-default-rtdb.firebaseio.com',
    storageBucket: 'ponto-551a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNkYExbJDe8MQs7PKiJTvIJQQsrGdVixI',
    appId: '1:196881712981:ios:0b32071a6906ddd63611dc',
    messagingSenderId: '196881712981',
    projectId: 'ponto-551a5',
    databaseURL: 'https://ponto-551a5-default-rtdb.firebaseio.com',
    storageBucket: 'ponto-551a5.appspot.com',
    iosClientId: '196881712981-996a6bolittms6a0hi1b85ig238dcph2.apps.googleusercontent.com',
    iosBundleId: 'com.example.relogioPonto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNkYExbJDe8MQs7PKiJTvIJQQsrGdVixI',
    appId: '1:196881712981:ios:0b32071a6906ddd63611dc',
    messagingSenderId: '196881712981',
    projectId: 'ponto-551a5',
    databaseURL: 'https://ponto-551a5-default-rtdb.firebaseio.com',
    storageBucket: 'ponto-551a5.appspot.com',
    iosClientId: '196881712981-996a6bolittms6a0hi1b85ig238dcph2.apps.googleusercontent.com',
    iosBundleId: 'com.example.relogioPonto',
  );
}
